name: example
description: Autoequal example
version: 1.0.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  autoequal: ^0.1.1

dev_dependencies:
  build_runner: ^1.10.4
  autoequal_gen: ^0.1.1
  test: ^1.15.4

dependency_overrides:
  autoequal:
    path: ../autoequal
  autoequal_gen:
    path: ../autoequal_gen