name: example
description: Autoequal example
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  autoequal: ^0.2.0

dev_dependencies:
  pedantic: ^1.11.0
  build_runner: ^1.11.5
  autoequal_gen: ^0.2.0
  test: ^1.16.5

dependency_overrides:
  autoequal:
    path: ../autoequal
  autoequal_gen:
    path: ../autoequal_gen