name: autoequal_gen
description: |
  Codegenerator which can simplify work with 'equatable'.
  It will generate 'List<Object> props' priviate extensions for all annotated classes.
version: 0.1.2
homepage: https://github.com/sunnydaydev/autoequal

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  analyzer: ^0.40.5
  build: ^1.5.0
  source_gen: ^0.9.8
  autoequal: ^0.1.2
  equatable: ^1.2.5

dev_dependencies:
  build_test: ^1.2.2
  build_runner: ^1.10.4
  test: ^1.15.4
  pedantic: ^1.9.0
